name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: athulkjose01/shareride:${{ github.sha }}

    - name: SSH to EC2 and Deploy
      uses: appleboy/scp-action@v0.1.4
      with:
        host: "13.60.166.171"        # Replace with your EC2 instance public IP
        username: "ubuntu"           # Use 'ubuntu' as the username
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: "athulkjose01/shareride:${{ github.sha }}"
        target: "/home/ubuntu/myapp" 

    - name: SSH to EC2 and run container
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: "13.60.166.171"        # Replace with your EC2 instance public IP
        username: "ubuntu"           # Use 'ubuntu' as the username
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull athulkjose01/shareride:${{ github.sha }}
          docker stop shareride || true
          docker rm shareride || true
          docker run -d --name shareride athulkjose01/shareride:${{ github.sha }}
