name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: athulkjose01/shareride:${{ github.sha }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: "13.60.166.171"        # Replace with your EC2 instance public IP
        username: "ubuntu"           # Use 'ubuntu' as the username
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull athulkjose01/shareride:${{ github.sha }}
          docker stop shareride || true
          docker rm shareride || true
          docker run -d --name shareride -p 8000:8000 athulkjose01/shareride:${{ github.sha }}
